//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PromiseCharm {
            get {
                return ((bool)(this["PromiseCharm"]));
            }
            set {
                this["PromiseCharm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AnsemReports {
            get {
                return ((bool)(this["AnsemReports"]));
            }
            set {
                this["AnsemReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Abilities {
            get {
                return ((bool)(this["Abilities"]));
            }
            set {
                this["Abilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TornPages {
            get {
                return ((bool)(this["TornPages"]));
            }
            set {
                this["TornPages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FinalForm {
            get {
                return ((bool)(this["FinalForm"]));
            }
            set {
                this["FinalForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Simulated {
            get {
                return ((bool)(this["Simulated"]));
            }
            set {
                this["Simulated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HundredAcre {
            get {
                return ((bool)(this["HundredAcre"]));
            }
            set {
                this["HundredAcre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Atlantica {
            get {
                return ((bool)(this["Atlantica"]));
            }
            set {
                this["Atlantica"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowX {
            get {
                return ((double)(this["WindowX"]));
            }
            set {
                this["WindowX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowY {
            get {
                return ((double)(this["WindowY"]));
            }
            set {
                this["WindowY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cure {
            get {
                return ((bool)(this["Cure"]));
            }
            set {
                this["Cure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SoraHeart {
            get {
                return ((bool)(this["SoraHeart"]));
            }
            set {
                this["SoraHeart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("570")]
        public double Width {
            get {
                return ((double)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("880")]
        public double Height {
            get {
                return ((double)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DragDrop {
            get {
                return ((bool)(this["DragDrop"]));
            }
            set {
                this["DragDrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WorldProgress {
            get {
                return ((bool)(this["WorldProgress"]));
            }
            set {
                this["WorldProgress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TopMost {
            get {
                return ((bool)(this["TopMost"]));
            }
            set {
                this["TopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FormsGrowth {
            get {
                return ((bool)(this["FormsGrowth"]));
            }
            set {
                this["FormsGrowth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinWorld {
            get {
                return ((bool)(this["MinWorld"]));
            }
            set {
                this["MinWorld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OldWorld {
            get {
                return ((bool)(this["OldWorld"]));
            }
            set {
                this["OldWorld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinCheck {
            get {
                return ((bool)(this["MinCheck"]));
            }
            set {
                this["MinCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OldCheck {
            get {
                return ((bool)(this["OldCheck"]));
            }
            set {
                this["OldCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinProg {
            get {
                return ((bool)(this["MinProg"]));
            }
            set {
                this["MinProg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OldProg {
            get {
                return ((bool)(this["OldProg"]));
            }
            set {
                this["OldProg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinNum {
            get {
                return ((bool)(this["MinNum"]));
            }
            set {
                this["MinNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OldNum {
            get {
                return ((bool)(this["OldNum"]));
            }
            set {
                this["OldNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainBG {
            get {
                return ((int)(this["MainBG"]));
            }
            set {
                this["MainBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomIcons {
            get {
                return ((bool)(this["CustomIcons"]));
            }
            set {
                this["CustomIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SeedHash {
            get {
                return ((bool)(this["SeedHash"]));
            }
            set {
                this["SeedHash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GhostItem {
            get {
                return ((bool)(this["GhostItem"]));
            }
            set {
                this["GhostItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoDetect {
            get {
                return ((bool)(this["AutoDetect"]));
            }
            set {
                this["AutoDetect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Level1 {
            get {
                return ((bool)(this["Level1"]));
            }
            set {
                this["Level1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Level50 {
            get {
                return ((bool)(this["Level50"]));
            }
            set {
                this["Level50"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Level99 {
            get {
                return ((bool)(this["Level99"]));
            }
            set {
                this["Level99"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckCount {
            get {
                return ((bool)(this["CheckCount"]));
            }
            set {
                this["CheckCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GhostMath {
            get {
                return ((bool)(this["GhostMath"]));
            }
            set {
                this["GhostMath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldLevel1 {
            get {
                return ((bool)(this["WorldLevel1"]));
            }
            set {
                this["WorldLevel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WorldLevel50 {
            get {
                return ((bool)(this["WorldLevel50"]));
            }
            set {
                this["WorldLevel50"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldLevel99 {
            get {
                return ((bool)(this["WorldLevel99"]));
            }
            set {
                this["WorldLevel99"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NextLevelCheck {
            get {
                return ((bool)(this["NextLevelCheck"]));
            }
            set {
                this["NextLevelCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldVisitLock {
            get {
                return ((bool)(this["WorldVisitLock"]));
            }
            set {
                this["WorldVisitLock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Puzzle {
            get {
                return ((bool)(this["Puzzle"]));
            }
            set {
                this["Puzzle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Synth {
            get {
                return ((bool)(this["Synth"]));
            }
            set {
                this["Synth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeathCounter {
            get {
                return ((bool)(this["DeathCounter"]));
            }
            set {
                this["DeathCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Legacy {
            get {
                return ((bool)(this["Legacy"]));
            }
            set {
                this["Legacy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntiForm {
            get {
                return ((bool)(this["AntiForm"]));
            }
            set {
                this["AntiForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtraChecks {
            get {
                return ((bool)(this["ExtraChecks"]));
            }
            set {
                this["ExtraChecks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Drives {
            get {
                return ((bool)(this["Drives"]));
            }
            set {
                this["Drives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TwilightTown {
            get {
                return ((bool)(this["TwilightTown"]));
            }
            set {
                this["TwilightTown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HollowBastion {
            get {
                return ((bool)(this["HollowBastion"]));
            }
            set {
                this["HollowBastion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BeastCastle {
            get {
                return ((bool)(this["BeastCastle"]));
            }
            set {
                this["BeastCastle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Olympus {
            get {
                return ((bool)(this["Olympus"]));
            }
            set {
                this["Olympus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Agrabah {
            get {
                return ((bool)(this["Agrabah"]));
            }
            set {
                this["Agrabah"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LandofDragons {
            get {
                return ((bool)(this["LandofDragons"]));
            }
            set {
                this["LandofDragons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisneyCastle {
            get {
                return ((bool)(this["DisneyCastle"]));
            }
            set {
                this["DisneyCastle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrideLands {
            get {
                return ((bool)(this["PrideLands"]));
            }
            set {
                this["PrideLands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PortRoyal {
            get {
                return ((bool)(this["PortRoyal"]));
            }
            set {
                this["PortRoyal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HalloweenTown {
            get {
                return ((bool)(this["HalloweenTown"]));
            }
            set {
                this["HalloweenTown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpaceParanoids {
            get {
                return ((bool)(this["SpaceParanoids"]));
            }
            set {
                this["SpaceParanoids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TWTNW {
            get {
                return ((bool)(this["TWTNW"]));
            }
            set {
                this["TWTNW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ColorHints {
            get {
                return ((bool)(this["ColorHints"]));
            }
            set {
                this["ColorHints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NewWorldLayout {
            get {
                return ((bool)(this["NewWorldLayout"]));
            }
            set {
                this["NewWorldLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OldWorldLayout {
            get {
                return ((bool)(this["OldWorldLayout"]));
            }
            set {
                this["OldWorldLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveProgress {
            get {
                return ((bool)(this["AutoSaveProgress"]));
            }
            set {
                this["AutoSaveProgress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WorldHighlight {
            get {
                return ((bool)(this["WorldHighlight"]));
            }
            set {
                this["WorldHighlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsingProgressionHints {
            get {
                return ((bool)(this["UsingProgressionHints"]));
            }
            set {
                this["UsingProgressionHints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldHintHighlight {
            get {
                return ((bool)(this["WorldHintHighlight"]));
            }
            set {
                this["WorldHintHighlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Disconnect {
            get {
                return ((bool)(this["Disconnect"]));
            }
            set {
                this["Disconnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConnect {
            get {
                return ((bool)(this["AutoConnect"]));
            }
            set {
                this["AutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveProgress2 {
            get {
                return ((bool)(this["AutoSaveProgress2"]));
            }
            set {
                this["AutoSaveProgress2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoLoadHints {
            get {
                return ((bool)(this["AutoLoadHints"]));
            }
            set {
                this["AutoLoadHints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GridWindowX {
            get {
                return ((double)(this["GridWindowX"]));
            }
            set {
                this["GridWindowX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GridWindowY {
            get {
                return ((double)(this["GridWindowY"]));
            }
            set {
                this["GridWindowY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double GridWindowWidth {
            get {
                return ((double)(this["GridWindowWidth"]));
            }
            set {
                this["GridWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("680")]
        public double GridWindowHeight {
            get {
                return ((double)(this["GridWindowHeight"]));
            }
            set {
                this["GridWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int GridWindowRows {
            get {
                return ((int)(this["GridWindowRows"]));
            }
            set {
                this["GridWindowRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int GridWindowColumns {
            get {
                return ((int)(this["GridWindowColumns"]));
            }
            set {
                this["GridWindowColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"Limit\":true,\"HadesCup\":true,\"GridCure1\":true,\"GridFire2\":true,\"GridThunder3\":tr" +
            "ue,\"GridCure2\":true,\"GridCure3\":true,\"GridMagnet1\":true,\"GridMagnet2\":true,\"Grid" +
            "Magnet3\":true,\"GridTornPage4\":true,\"Report9\":true,\"GridTornPage2\":true,\"GridTorn" +
            "Page3\":true,\"GridTornPage1\":true,\"Report1\":true,\"Report3\":true,\"Report2\":true,\"R" +
            "eport5\":true,\"Report4\":true,\"Report7\":true,\"Report6\":true,\"Feather\":true,\"GridTo" +
            "rnPage5\":true,\"Report12\":true,\"OnceMore\":true,\"Report8\":true,\"GridReflect3\":true" +
            ",\"GridMunnyPouch1\":true,\"OlympusStone\":true,\"GridMunnyPouch2\":true,\"Final\":true," +
            "\"Report13\":true,\"GridBlizzard1\":true,\"GridBlizzard2\":true,\"GridBlizzard3\":true,\"" +
            "Nonexistence\":true,\"Baseball\":true,\"PromiseCharm\":true,\"UnknownDisk\":true,\"GridT" +
            "hunder1\":true,\"GridFire3\":true,\"GridFire1\":true,\"SecondChance\":true,\"Wisdom\":tru" +
            "e,\"Report10\":true,\"Ukulele\":true,\"Valor\":true,\"Master\":true,\"Connection\":true,\"L" +
            "amp\":true,\"Report11\":true,\"GridThunder2\":true,\"Peace\":true,\"GridReflect1\":true,\"" +
            "GridReflect2\":true,\"Kanga\":true,\"GridSephiroth\":true,\"Xigbar\":true,\"GridDataSaix" +
            "\":true,\"OCPete\":true,\"Windows\":true,\"GridLingeringWill\":true,\"Presents\":true,\"Ge" +
            "nieJafar\":true,\"AnsemStudy\":true,\"DarkThorn\":true,\"NewDay\":true,\"Hyenas2\":true,\"" +
            "GridVolcanoLord\":true,\"Hydra\":true,\"Scar\":true,\"Roxas\":true,\"Gambler\":true,\"Grid" +
            "DataXaldin\":true,\"Sandlot\":true,\"Mansion\":true,\"GridFinalXemnas\":true,\"GridLexae" +
            "us\":true,\"Abu\":true,\"BetwixtAndBetween\":true,\"GroundShaker\":true,\"Struggle\":true" +
            ",\"GridDataAxel\":true,\"Barbossa\":true,\"Axel\":true,\"TwilightThorn\":true,\"GridHercu" +
            "les\":true,\"Fight2\":true,\"OldPete\":true,\"Cerberus\":true,\"Drive6\":true,\"Fight1\":tr" +
            "ue,\"SolarSailer\":true,\"GridArmoredXemnas1\":true,\"Barrels\":true,\"AuronStatue\":tru" +
            "e,\"Hades\":true,\"Mountain\":true,\"Screens\":true,\"ThroneRoom\":true,\"OCDemyx\":true,\"" +
            "Luxord\":true,\"Drive2\":false,\"GridRiku\":true,\"Drive7\":true,\"Lords\":true,\"GridShad" +
            "owStalker\":true,\"HostileProgram\":true,\"PrisonKeeper\":true,\"BoatPete\":true,\"Drago" +
            "ons\":true,\"GridSeifer\":true,\"Town\":true,\"GridArmoredXemnas2\":true,\"Beast\":true,\"" +
            "GridDataLuxord\":true,\"MCP\":true,\"Cave\":true,\"GridMarluxiaData\":true,\"Axel1\":true" +
            ",\"DCPete\":true,\"StormRider\":true,\"Drive3\":true,\"CandyCaneLane\":true,\"Drive4\":tru" +
            "e,\"Xaldin\":true,\"GridDataRoxas\":true,\"GridLexaeusData\":true,\"StarryHill\":true,\"S" +
            "tation\":true,\"Grid7Drives\":true,\"GridVivi\":true,\"GridDataXemnas\":true,\"GridVexen" +
            "\":true,\"Saix\":true,\"Corridor\":true,\"Bailey\":true,\"Ursula\":true,\"Piglet\":true,\"Gr" +
            "idZexion\":true,\"GridLarxeneData\":true,\"Hyenas1\":true,\"GridSetzer\":true,\"GridClou" +
            "d\":true,\"Missions\":true,\"GridDataXigbar\":true,\"MysteriousTower\":true,\"Sark\":true" +
            ",\"Transport\":true,\"GridTifa\":true,\"Simba\":true,\"Chasm\":true,\"Tutorial\":true,\"Fin" +
            "alFantasy\":true,\"Rabbit\":true,\"GridHayner\":true,\"ShanYu\":true,\"Experiment\":true," +
            "\"GrimReaper\":true,\"SpookyCave\":true,\"OogieBoogie\":true,\"1Minute\":true,\"HBDemyx\":" +
            "true,\"Urns\":true,\"ComputerRoom\":true,\"Summit\":true,\"Minnie\":true,\"GridDataDemyx\"" +
            ":true,\"Thresholder\":true,\"Dancers\":true,\"TreasureRoom\":true,\"Xemnas1\":true,\"Grid" +
            "Yuffie\":true,\"GrimReaper1\":true,\"Medallions\":true,\"GridMarluxia\":true,\"GridBlizz" +
            "ardLord\":true,\"GridLeon\":true,\"Drive5\":true,\"Minigame\":true,\"Children\":true,\"Gri" +
            "dZexionData\":true,\"1000Heartless\":true,\"GridVexenData\":true,\"GridLarxene\":true,\"" +
            "GridDataFinalXemnas\":true,\"ChestTT\":true,\"ChestSP\":true,\"KingsLetter1\":true,\"Che" +
            "stHB\":true,\"ChestHT\":true,\"RikuWep2\":true,\"AuronWep1\":true,\"AuronWep2\":true,\"Jac" +
            "kWep2\":true,\"ChestAG\":true,\"BeastWep1\":true,\"RikuWep1\":true,\"ChestOC\":true,\"Mula" +
            "nWep2\":true,\"MembershipCard2\":true,\"ChestDC\":true,\"SimbaWep2\":true,\"SimbaWep1\":t" +
            "rue,\"ChestHAW\":true,\"SparrowWep2\":true,\"SparrowWep1\":true,\"Sketches\":true,\"Membe" +
            "rshipCard1\":true,\"MulanWep1\":true,\"ChestBC\":true,\"AladdinWep2\":true,\"AladdinWep1" +
            "\":true,\"TronWep2\":true,\"BeastWep2\":true,\"ChestCoR\":true,\"KingsLetter2\":true,\"Che" +
            "stLoD\":true,\"ChestPL\":true,\"TronWep1\":true,\"IceCream2\":true,\"IceCream3\":true,\"Ch" +
            "estPR\":true,\"IceCream1\":true,\"JackWep1\":true,\"ChestSTT\":true,\"ChestTWTNW\":true,\"" +
            "ForcingFinalCounts\":false,\"Glide4\":false,\"Glide3\":false,\"Glide2\":false,\"Glide1\":" +
            "false,\"AerialDodge4\":false,\"AerialDodge3\":false,\"AerialDodge2\":false,\"AerialDodg" +
            "e1\":false,\"DodgeRoll4\":false,\"DodgeRoll3\":false,\"DodgeRoll2\":false,\"DodgeRoll1\":" +
            "false,\"QuickRun4\":false,\"QuickRun3\":false,\"QuickRun2\":false,\"QuickRun1\":false,\"H" +
            "ighJump4\":false,\"HighJump3\":false,\"HighJump2\":false,\"HighJump1\":false,\"Anti\":fal" +
            "se,\"Final7\":false,\"Final6\":false,\"Final5\":false,\"Final4\":false,\"Final3\":false,\"F" +
            "inal2\":false,\"Master7\":false,\"Master6\":false,\"Master5\":false,\"Master4\":false,\"Ma" +
            "ster3\":false,\"Master2\":false,\"Limit7\":false,\"Limit6\":false,\"Limit5\":false,\"Limit" +
            "4\":false,\"Limit3\":false,\"Limit2\":false,\"Wisdom7\":false,\"Wisdom6\":false,\"Wisdom5\"" +
            ":false,\"Wisdom4\":false,\"Wisdom3\":false,\"Wisdom2\":false,\"Valor7\":false,\"Valor6\":f" +
            "alse,\"Valor5\":false,\"Valor4\":false,\"Valor3\":false,\"Valor2\":false}")]
        public string GridSettings {
            get {
                return ((string)(this["GridSettings"]));
            }
            set {
                this["GridSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int GridWindowNumReports {
            get {
                return ((int)(this["GridWindowNumReports"]));
            }
            set {
                this["GridWindowNumReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26")]
        public int GridWindowNumUnlocks {
            get {
                return ((int)(this["GridWindowNumUnlocks"]));
            }
            set {
                this["GridWindowNumUnlocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF696969")]
        public global::System.Windows.Media.Color UnmarkedColor {
            get {
                return ((global::System.Windows.Media.Color)(this["UnmarkedColor"]));
            }
            set {
                this["UnmarkedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF006400")]
        public global::System.Windows.Media.Color MarkedColor {
            get {
                return ((global::System.Windows.Media.Color)(this["MarkedColor"]));
            }
            set {
                this["MarkedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFA500")]
        public global::System.Windows.Media.Color AnnotatedColor {
            get {
                return ((global::System.Windows.Media.Color)(this["AnnotatedColor"]));
            }
            set {
                this["AnnotatedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF6700CC")]
        public global::System.Windows.Media.Color BingoColor {
            get {
                return ((global::System.Windows.Media.Color)(this["BingoColor"]));
            }
            set {
                this["BingoColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color HintColor {
            get {
                return ((global::System.Windows.Media.Color)(this["HintColor"]));
            }
            set {
                this["HintColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GridBingoLogic {
            get {
                return ((bool)(this["GridBingoLogic"]));
            }
            set {
                this["GridBingoLogic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GridBattleshipLogic {
            get {
                return ((bool)(this["GridBattleshipLogic"]));
            }
            set {
                this["GridBattleshipLogic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SavePreviousGridSetting {
            get {
                return ((bool)(this["SavePreviousGridSetting"]));
            }
            set {
                this["SavePreviousGridSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GridOptionsWindowX {
            get {
                return ((double)(this["GridOptionsWindowX"]));
            }
            set {
                this["GridOptionsWindowX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GridOptionsWindowY {
            get {
                return ((double)(this["GridOptionsWindowY"]));
            }
            set {
                this["GridOptionsWindowY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double GridOptionsWindowHeight {
            get {
                return ((double)(this["GridOptionsWindowHeight"]));
            }
            set {
                this["GridOptionsWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double GridOptionsWindowWidth {
            get {
                return ((double)(this["GridOptionsWindowWidth"]));
            }
            set {
                this["GridOptionsWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TelevoIcons {
            get {
                return ((bool)(this["TelevoIcons"]));
            }
            set {
                this["TelevoIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SonicIcons {
            get {
                return ((bool)(this["SonicIcons"]));
            }
            set {
                this["SonicIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldChestLock {
            get {
                return ((bool)(this["WorldChestLock"]));
            }
            set {
                this["WorldChestLock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF87CEFA")]
        public global::System.Windows.Media.Color BattleshipMissColor {
            get {
                return ((global::System.Windows.Media.Color)(this["BattleshipMissColor"]));
            }
            set {
                this["BattleshipMissColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color BattleshipHitColor {
            get {
                return ((global::System.Windows.Media.Color)(this["BattleshipHitColor"]));
            }
            set {
                this["BattleshipHitColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFC0CB")]
        public global::System.Windows.Media.Color BattleshipSunkColor {
            get {
                return ((global::System.Windows.Media.Color)(this["BattleshipSunkColor"]));
            }
            set {
                this["BattleshipSunkColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double ColorWindowWidth {
            get {
                return ((double)(this["ColorWindowWidth"]));
            }
            set {
                this["ColorWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double ColorWindowHeight {
            get {
                return ((double)(this["ColorWindowHeight"]));
            }
            set {
                this["ColorWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ColorWindowY {
            get {
                return ((double)(this["ColorWindowY"]));
            }
            set {
                this["ColorWindowY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ColorWindowX {
            get {
                return ((double)(this["ColorWindowX"]));
            }
            set {
                this["ColorWindowX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int GridWindowNumChestLocks {
            get {
                return ((int)(this["GridWindowNumChestLocks"]));
            }
            set {
                this["GridWindowNumChestLocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GridFogOfWar {
            get {
                return ((bool)(this["GridFogOfWar"]));
            }
            set {
                this["GridFogOfWar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GridBattleshipRandomCount {
            get {
                return ((bool)(this["GridBattleshipRandomCount"]));
            }
            set {
                this["GridBattleshipRandomCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"W\": 1, \"E\": 1, \"N\": 1, \"S\": 1, \"NW\": 0, \"NE\": 0, \"SW\": 0, \"SE\": 0}")]
        public string GridFogOfWarSpan {
            get {
                return ((string)(this["GridFogOfWarSpan"]));
            }
            set {
                this["GridFogOfWarSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[2, 3, 3, 4, 5]")]
        public string GridShipSizes {
            get {
                return ((string)(this["GridShipSizes"]));
            }
            set {
                this["GridShipSizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int GridMaxShipCount {
            get {
                return ((int)(this["GridMaxShipCount"]));
            }
            set {
                this["GridMaxShipCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int GridMinShipCount {
            get {
                return ((int)(this["GridMinShipCount"]));
            }
            set {
                this["GridMinShipCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FogIconSetting {
            get {
                return ((bool)(this["FogIconSetting"]));
            }
            set {
                this["FogIconSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GridCustomImages {
            get {
                return ((bool)(this["GridCustomImages"]));
            }
            set {
                this["GridCustomImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double ObjectiveWindowHeight {
            get {
                return ((double)(this["ObjectiveWindowHeight"]));
            }
            set {
                this["ObjectiveWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double ObjectiveWindowWidth {
            get {
                return ((double)(this["ObjectiveWindowWidth"]));
            }
            set {
                this["ObjectiveWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ObjectiveWindowX {
            get {
                return ((double)(this["ObjectiveWindowX"]));
            }
            set {
                this["ObjectiveWindowX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ObjectiveWindowY {
            get {
                return ((double)(this["ObjectiveWindowY"]));
            }
            set {
                this["ObjectiveWindowY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ObjectiveTelevo {
            get {
                return ((bool)(this["ObjectiveTelevo"]));
            }
            set {
                this["ObjectiveTelevo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ObjectiveSonic {
            get {
                return ((bool)(this["ObjectiveSonic"]));
            }
            set {
                this["ObjectiveSonic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ObjectiveCustom {
            get {
                return ((bool)(this["ObjectiveCustom"]));
            }
            set {
                this["ObjectiveCustom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF696969")]
        public global::System.Windows.Media.Color ObjUnmarkedColorButton {
            get {
                return ((global::System.Windows.Media.Color)(this["ObjUnmarkedColorButton"]));
            }
            set {
                this["ObjUnmarkedColorButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF006400")]
        public global::System.Windows.Media.Color ObjCollectedColorButton {
            get {
                return ((global::System.Windows.Media.Color)(this["ObjCollectedColorButton"]));
            }
            set {
                this["ObjCollectedColorButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFA500")]
        public global::System.Windows.Media.Color ObjAnnotatedColorButton {
            get {
                return ((global::System.Windows.Media.Color)(this["ObjAnnotatedColorButton"]));
            }
            set {
                this["ObjAnnotatedColorButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFC0CB")]
        public global::System.Windows.Media.Color ObjCompletedColorButton {
            get {
                return ((global::System.Windows.Media.Color)(this["ObjCompletedColorButton"]));
            }
            set {
                this["ObjCompletedColorButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldVisitLock2 {
            get {
                return ((bool)(this["WorldVisitLock2"]));
            }
            set {
                this["WorldVisitLock2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GridBunterLogic {
            get {
                return ((bool)(this["GridBunterLogic"]));
            }
            set {
                this["GridBunterLogic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EmblemCount {
            get {
                return ((bool)(this["EmblemCount"]));
            }
            set {
                this["EmblemCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GridTrackerStartup {
            get {
                return ((bool)(this["GridTrackerStartup"]));
            }
            set {
                this["GridTrackerStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ObjTrackerStartup {
            get {
                return ((bool)(this["ObjTrackerStartup"]));
            }
            set {
                this["ObjTrackerStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OneHourModeToggle {
            get {
                return ((bool)(this["OneHourModeToggle"]));
            }
            set {
                this["OneHourModeToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DartsModeToggle {
            get {
                return ((bool)(this["DartsModeToggle"]));
            }
            set {
                this["DartsModeToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClassicRowSize {
            get {
                return ((bool)(this["ClassicRowSize"]));
            }
            set {
                this["ClassicRowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GOAWorldLayout {
            get {
                return ((bool)(this["GOAWorldLayout"]));
            }
            set {
                this["GOAWorldLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GridColoredHints {
            get {
                return ((bool)(this["GridColoredHints"]));
            }
            set {
                this["GridColoredHints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int GridColoredHintsDistance {
            get {
                return ((int)(this["GridColoredHintsDistance"]));
            }
            set {
                this["GridColoredHintsDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSaveProgress3 {
            get {
                return ((bool)(this["AutoSaveProgress3"]));
            }
            set {
                this["AutoSaveProgress3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KhTrackerSettings/GameModes/OneHourModeAssets.json")]
        public string OneHourModeAssetsFilepath {
            get {
                return ((string)(this["OneHourModeAssetsFilepath"]));
            }
            set {
                this["OneHourModeAssetsFilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KhTrackerSettings/GameModes/DartsModeAssets.json")]
        public string DartsModeAssetsFilepath {
            get {
                return ((string)(this["DartsModeAssetsFilepath"]));
            }
            set {
                this["DartsModeAssetsFilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Custom1HRAssets {
            get {
                return ((bool)(this["Custom1HRAssets"]));
            }
            set {
                this["Custom1HRAssets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomDartsAssets {
            get {
                return ((bool)(this["CustomDartsAssets"]));
            }
            set {
                this["CustomDartsAssets"] = value;
            }
        }
    }
}
