//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PromiseCharm {
            get {
                return ((bool)(this["PromiseCharm"]));
            }
            set {
                this["PromiseCharm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AnsemReports {
            get {
                return ((bool)(this["AnsemReports"]));
            }
            set {
                this["AnsemReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Abilities {
            get {
                return ((bool)(this["Abilities"]));
            }
            set {
                this["Abilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TornPages {
            get {
                return ((bool)(this["TornPages"]));
            }
            set {
                this["TornPages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FinalForm {
            get {
                return ((bool)(this["FinalForm"]));
            }
            set {
                this["FinalForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Simulated {
            get {
                return ((bool)(this["Simulated"]));
            }
            set {
                this["Simulated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HundredAcre {
            get {
                return ((bool)(this["HundredAcre"]));
            }
            set {
                this["HundredAcre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Atlantica {
            get {
                return ((bool)(this["Atlantica"]));
            }
            set {
                this["Atlantica"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowX {
            get {
                return ((double)(this["WindowX"]));
            }
            set {
                this["WindowX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowY {
            get {
                return ((double)(this["WindowY"]));
            }
            set {
                this["WindowY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cure {
            get {
                return ((bool)(this["Cure"]));
            }
            set {
                this["Cure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SoraHeart {
            get {
                return ((bool)(this["SoraHeart"]));
            }
            set {
                this["SoraHeart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("570")]
        public double Width {
            get {
                return ((double)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("880")]
        public double Height {
            get {
                return ((double)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DragDrop {
            get {
                return ((bool)(this["DragDrop"]));
            }
            set {
                this["DragDrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WorldProgress {
            get {
                return ((bool)(this["WorldProgress"]));
            }
            set {
                this["WorldProgress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TopMost {
            get {
                return ((bool)(this["TopMost"]));
            }
            set {
                this["TopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FormsGrowth {
            get {
                return ((bool)(this["FormsGrowth"]));
            }
            set {
                this["FormsGrowth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinWorld {
            get {
                return ((bool)(this["MinWorld"]));
            }
            set {
                this["MinWorld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OldWorld {
            get {
                return ((bool)(this["OldWorld"]));
            }
            set {
                this["OldWorld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinCheck {
            get {
                return ((bool)(this["MinCheck"]));
            }
            set {
                this["MinCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OldCheck {
            get {
                return ((bool)(this["OldCheck"]));
            }
            set {
                this["OldCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinProg {
            get {
                return ((bool)(this["MinProg"]));
            }
            set {
                this["MinProg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OldProg {
            get {
                return ((bool)(this["OldProg"]));
            }
            set {
                this["OldProg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinNum {
            get {
                return ((bool)(this["MinNum"]));
            }
            set {
                this["MinNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OldNum {
            get {
                return ((bool)(this["OldNum"]));
            }
            set {
                this["OldNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainBG {
            get {
                return ((int)(this["MainBG"]));
            }
            set {
                this["MainBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomIcons {
            get {
                return ((bool)(this["CustomIcons"]));
            }
            set {
                this["CustomIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SeedHash {
            get {
                return ((bool)(this["SeedHash"]));
            }
            set {
                this["SeedHash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GhostItem {
            get {
                return ((bool)(this["GhostItem"]));
            }
            set {
                this["GhostItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoDetect {
            get {
                return ((bool)(this["AutoDetect"]));
            }
            set {
                this["AutoDetect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Level1 {
            get {
                return ((bool)(this["Level1"]));
            }
            set {
                this["Level1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Level50 {
            get {
                return ((bool)(this["Level50"]));
            }
            set {
                this["Level50"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Level99 {
            get {
                return ((bool)(this["Level99"]));
            }
            set {
                this["Level99"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckCount {
            get {
                return ((bool)(this["CheckCount"]));
            }
            set {
                this["CheckCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GhostMath {
            get {
                return ((bool)(this["GhostMath"]));
            }
            set {
                this["GhostMath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldLevel1 {
            get {
                return ((bool)(this["WorldLevel1"]));
            }
            set {
                this["WorldLevel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WorldLevel50 {
            get {
                return ((bool)(this["WorldLevel50"]));
            }
            set {
                this["WorldLevel50"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldLevel99 {
            get {
                return ((bool)(this["WorldLevel99"]));
            }
            set {
                this["WorldLevel99"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NextLevelCheck {
            get {
                return ((bool)(this["NextLevelCheck"]));
            }
            set {
                this["NextLevelCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldVisitLock {
            get {
                return ((bool)(this["WorldVisitLock"]));
            }
            set {
                this["WorldVisitLock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Puzzle {
            get {
                return ((bool)(this["Puzzle"]));
            }
            set {
                this["Puzzle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Synth {
            get {
                return ((bool)(this["Synth"]));
            }
            set {
                this["Synth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeathCounter {
            get {
                return ((bool)(this["DeathCounter"]));
            }
            set {
                this["DeathCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Legacy {
            get {
                return ((bool)(this["Legacy"]));
            }
            set {
                this["Legacy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntiForm {
            get {
                return ((bool)(this["AntiForm"]));
            }
            set {
                this["AntiForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtraChecks {
            get {
                return ((bool)(this["ExtraChecks"]));
            }
            set {
                this["ExtraChecks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Drives {
            get {
                return ((bool)(this["Drives"]));
            }
            set {
                this["Drives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TwilightTown {
            get {
                return ((bool)(this["TwilightTown"]));
            }
            set {
                this["TwilightTown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HollowBastion {
            get {
                return ((bool)(this["HollowBastion"]));
            }
            set {
                this["HollowBastion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BeastCastle {
            get {
                return ((bool)(this["BeastCastle"]));
            }
            set {
                this["BeastCastle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Olympus {
            get {
                return ((bool)(this["Olympus"]));
            }
            set {
                this["Olympus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Agrabah {
            get {
                return ((bool)(this["Agrabah"]));
            }
            set {
                this["Agrabah"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LandofDragons {
            get {
                return ((bool)(this["LandofDragons"]));
            }
            set {
                this["LandofDragons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisneyCastle {
            get {
                return ((bool)(this["DisneyCastle"]));
            }
            set {
                this["DisneyCastle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrideLands {
            get {
                return ((bool)(this["PrideLands"]));
            }
            set {
                this["PrideLands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PortRoyal {
            get {
                return ((bool)(this["PortRoyal"]));
            }
            set {
                this["PortRoyal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HalloweenTown {
            get {
                return ((bool)(this["HalloweenTown"]));
            }
            set {
                this["HalloweenTown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpaceParanoids {
            get {
                return ((bool)(this["SpaceParanoids"]));
            }
            set {
                this["SpaceParanoids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TWTNW {
            get {
                return ((bool)(this["TWTNW"]));
            }
            set {
                this["TWTNW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ColorHints {
            get {
                return ((bool)(this["ColorHints"]));
            }
            set {
                this["ColorHints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NewWorldLayout {
            get {
                return ((bool)(this["NewWorldLayout"]));
            }
            set {
                this["NewWorldLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OldWorldLayout {
            get {
                return ((bool)(this["OldWorldLayout"]));
            }
            set {
                this["OldWorldLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSaveProgress {
            get {
                return ((bool)(this["AutoSaveProgress"]));
            }
            set {
                this["AutoSaveProgress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WorldHighlight {
            get {
                return ((bool)(this["WorldHighlight"]));
            }
            set {
                this["WorldHighlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsingProgressionHints {
            get {
                return ((bool)(this["UsingProgressionHints"]));
            }
            set {
                this["UsingProgressionHints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldHintHighlight {
            get {
                return ((bool)(this["WorldHintHighlight"]));
            }
            set {
                this["WorldHintHighlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Disconnect {
            get {
                return ((bool)(this["Disconnect"]));
            }
            set {
                this["Disconnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConnect {
            get {
                return ((bool)(this["AutoConnect"]));
            }
            set {
                this["AutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSaveProgress2 {
            get {
                return ((bool)(this["AutoSaveProgress2"]));
            }
            set {
                this["AutoSaveProgress2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GridWindowX {
            get {
                return ((double)(this["GridWindowX"]));
            }
            set {
                this["GridWindowX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GridWindowY {
            get {
                return ((double)(this["GridWindowY"]));
            }
            set {
                this["GridWindowY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double GridWindowWidth {
            get {
                return ((double)(this["GridWindowWidth"]));
            }
            set {
                this["GridWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("680")]
        public double GridWindowHeight {
            get {
                return ((double)(this["GridWindowHeight"]));
            }
            set {
                this["GridWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int GridWindowRows {
            get {
                return ((int)(this["GridWindowRows"]));
            }
            set {
                this["GridWindowRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int GridWindowColumns {
            get {
                return ((int)(this["GridWindowColumns"]));
            }
            set {
                this["GridWindowColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"Picture\":true,\"Limit\":true,\"HadesCup\":true,\"GridCure1\":true,\"AladdinWep\":true,\"" +
            "GridFire2\":true,\"GridThunder3\":true,\"MulanWep\":true,\"TronWep\":true,\"GridCure2\":t" +
            "rue,\"GridCure3\":true,\"GridMagnet1\":true,\"GridMagnet2\":true,\"GridMagnet3\":true,\"G" +
            "ridTornPage4\":true,\"Report9\":true,\"GridTornPage2\":true,\"GridTornPage3\":true,\"Gri" +
            "dTornPage1\":true,\"Report1\":true,\"Report3\":true,\"Report2\":true,\"Report5\":true,\"Re" +
            "port4\":false,\"Report7\":true,\"Report6\":true,\"MembershipCard\":true,\"Feather\":true," +
            "\"IceCream\":true,\"GridTornPage5\":true,\"Report12\":true,\"OnceMore\":true,\"Report8\":t" +
            "rue,\"GridReflect3\":true,\"GridMunnyPouch1\":true,\"OlympusStone\":true,\"GridMunnyPou" +
            "ch2\":true,\"Final\":true,\"Report13\":false,\"GridBlizzard1\":true,\"GridBlizzard2\":tru" +
            "e,\"GridBlizzard3\":true,\"Nonexistence\":true,\"Baseball\":true,\"PromiseCharm\":true,\"" +
            "SimbaWep\":true,\"UnknownDisk\":true,\"BeastWep\":true,\"GridThunder1\":true,\"GridFire3" +
            "\":true,\"GridFire1\":true,\"SecondChance\":true,\"Wisdom\":true,\"Report10\":true,\"Ukule" +
            "le\":true,\"Valor\":true,\"SparrowWep\":true,\"AuronWep\":true,\"MunnyPouch1\":true,\"Mast" +
            "er\":true,\"MunnyPouch2\":true,\"Connection\":true,\"Lamp\":true,\"Report11\":true,\"GridT" +
            "hunder2\":true,\"JackWep\":true,\"Peace\":true,\"GridReflect1\":true,\"GridReflect2\":tru" +
            "e,\"Kanga\":true,\"GridSephiroth\":true,\"Xigbar\":true,\"GridDataSaix\":true,\"OCPete\":t" +
            "rue,\"Windows\":true,\"GridLingeringWill\":true,\"Presents\":true,\"GenieJafar\":true,\"A" +
            "nsemStudy\":true,\"DarkThorn\":true,\"NewDay\":true,\"Hyenas2\":true,\"GridVolcanoLord\":" +
            "true,\"Hydra\":true,\"Scar\":true,\"Roxas\":true,\"Gambler\":true,\"GridDataXaldin\":true," +
            "\"Sandlot\":true,\"Mansion\":true,\"GridFinalXemnas\":true,\"GridLexaeus\":true,\"Abu\":tr" +
            "ue,\"BetwixtAndBetween\":true,\"GroundShaker\":true,\"Struggle\":true,\"GridDataAxel\":t" +
            "rue,\"Barbossa\":true,\"Axel\":true,\"TwilightThorn\":true,\"GridHercules\":true,\"Fight2" +
            "\":true,\"OldPete\":true,\"Cerberus\":true,\"Drive6\":true,\"Fight1\":true,\"Carpet\":true," +
            "\"SolarSailer\":true,\"GridArmoredXemnas1\":true,\"Barrels\":true,\"AuronStatue\":true,\"" +
            "Hades\":true,\"Mountain\":true,\"Screens\":true,\"ThroneRoom\":true,\"OCDemyx\":true,\"Lux" +
            "ord\":true,\"Drive2\":true,\"GridRiku\":true,\"Drive7\":true,\"Lords\":true,\"GridShadowSt" +
            "alker\":true,\"HostileProgram\":true,\"PrisonKeeper\":true,\"BoatPete\":true,\"Dragoons\"" +
            ":true,\"GridSeifer\":true,\"Town\":true,\"GridArmoredXemnas2\":true,\"Beast\":true,\"Grid" +
            "DataLuxord\":true,\"MCP\":true,\"Cave\":true,\"GridMarluxiaData\":true,\"Axel1\":true,\"DC" +
            "Pete\":true,\"StormRider\":true,\"Drive3\":true,\"CandyCaneLane\":true,\"Drive4\":true,\"X" +
            "aldin\":true,\"GridDataRoxas\":true,\"GridLexaeusData\":true,\"StarryHill\":true,\"Stati" +
            "on\":true,\"Grid7Drives\":true,\"GridVivi\":true,\"GridDataXemnas\":true,\"GridVexen\":tr" +
            "ue,\"Saix\":true,\"Corridor\":true,\"Bailey\":true,\"Ursula\":true,\"Piglet\":true,\"GridZe" +
            "xion\":true,\"GridLarxeneData\":true,\"Hyenas1\":true,\"GridSetzer\":true,\"GridCloud\":t" +
            "rue,\"Missions\":true,\"GridDataXigbar\":true,\"MysteriousTower\":true,\"Sark\":true,\"Tr" +
            "ansport\":true,\"GridTifa\":true,\"Simba\":true,\"Chasm\":true,\"Tutorial\":true,\"FinalFa" +
            "ntasy\":true,\"Rabbit\":true,\"GridHayner\":true,\"ShanYu\":true,\"Experiment\":true,\"Gri" +
            "mReaper\":true,\"SpookyCave\":true,\"OogieBoogie\":true,\"1Minute\":true,\"HBDemyx\":true" +
            ",\"Urns\":true,\"ComputerRoom\":true,\"Summit\":true,\"Minnie\":true,\"GridDataDemyx\":tru" +
            "e,\"Thresholder\":true,\"Dancers\":true,\"TreasureRoom\":true,\"Xemnas1\":true,\"GridYuff" +
            "ie\":true,\"GrimReaper1\":true,\"Medallions\":true,\"GridMarluxia\":true,\"GridBlizzardL" +
            "ord\":true,\"GridLeon\":true,\"Drive5\":true,\"Minigame\":true,\"Children\":true,\"GridZex" +
            "ionData\":true,\"1000Heartless\":true,\"GridVexenData\":true,\"GridLarxene\":true,\"Glob" +
            "alBingoLogic\":false}\r\n")]
        public string GridSettings {
            get {
                return ((string)(this["GridSettings"]));
            }
            set {
                this["GridSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int GridWindowNumReports {
            get {
                return ((int)(this["GridWindowNumReports"]));
            }
            set {
                this["GridWindowNumReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int GridWindowNumUnlocks {
            get {
                return ((int)(this["GridWindowNumUnlocks"]));
            }
            set {
                this["GridWindowNumUnlocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF696969")]
        public global::System.Windows.Media.Color UnmarkedColor {
            get {
                return ((global::System.Windows.Media.Color)(this["UnmarkedColor"]));
            }
            set {
                this["UnmarkedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008000")]
        public global::System.Windows.Media.Color MarkedColor {
            get {
                return ((global::System.Windows.Media.Color)(this["MarkedColor"]));
            }
            set {
                this["MarkedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFA500")]
        public global::System.Windows.Media.Color AnnotatedColor {
            get {
                return ((global::System.Windows.Media.Color)(this["AnnotatedColor"]));
            }
            set {
                this["AnnotatedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF800080")]
        public global::System.Windows.Media.Color BingoColor {
            get {
                return ((global::System.Windows.Media.Color)(this["BingoColor"]));
            }
            set {
                this["BingoColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GridWindowBingoLogic {
            get {
                return ((bool)(this["GridWindowBingoLogic"]));
            }
            set {
                this["GridWindowBingoLogic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GridWindowBattleshipLogic {
            get {
                return ((bool)(this["GridWindowBattleshipLogic"]));
            }
            set {
                this["GridWindowBattleshipLogic"] = value;
            }
        }
    }
}
