using System;
using System.Collections.Generic;
using System.Linq;

namespace KhTracker
{
    public class Codes
    {
        //Convert tracker world internal names to readable names
        public static string GetHintTextName(string worldName)
        {
            switch (worldName)
            {
                case "SimulatedTwilightTown":
                    return "Simulated Twilight Town";
                case "TwilightTown":
                    return "Twilight Town";
                case "HollowBastion":
                    return "Hollow Bastion";
                case "LandofDragons":
                    return "Land of Dragons";
                case "BeastsCastle":
                    return "Beast's Castle";
                case "OlympusColiseum":
                    return "Olympus Coliseum";
                case "DisneyCastle":
                    return "Disney Castle";
                case "PortRoyal":
                    return "Port Royal";
                case "HalloweenTown":
                    return "Halloween Town";
                case "PrideLands":
                    return "Pride Lands";
                case "HundredAcreWood":
                    return "Hundred Acre Wood";
                case "SpaceParanoids":
                    return "Space Paranoids";
                case "DriveForms":
                    return "Drive Forms";
                case "SorasHeart":
                    return "Sora's Heart";
                case "PuzzSynth":
                    return "Creations";
                default:
                    return worldName;
            }
        }

        //Convert seed gen world names to tracker internal names
        public static string GetWorldName(string worldName)
        {
            switch (worldName)
            {
                case "Simulated Twilight Town":
                    return "SimulatedTwilightTown";
                case "Twilight Town":
                    return "TwilightTown";
                case "Hollow Bastion":
                    return "HollowBastion";
                case "Land of Dragons":
                    return "LandofDragons";
                case "Beast's Castle":
                    return "BeastsCastle";
                case "Olympus Coliseum":
                    return "OlympusColiseum";
                case "Disney Castle":
                    return "DisneyCastle";
                case "Port Royal":
                    return "PortRoyal";
                case "Halloween Town":
                    return "HalloweenTown";
                case "Pride Lands":
                    return "PrideLands";
                case "Hundred Acre Wood":
                    return "HundredAcreWood";
                case "Space Paranoids":
                    return "SpaceParanoids";
                case "Drive Forms":
                    return "DriveForms";
                case "Sora's Heart":
                    return "SorasHeart";
                case "Creations":
                    return "PuzzSynth";
                default:
                    return worldName;
            }
        }

        //Convert seed gen item Ids to tracker item names
        public static string ConvertSeedGenName(int itemID, bool usegenName = false)
        {
            if (seedgenItemID.ContainsKey(itemID))
            {
                if (usegenName)
                    return seedgenItemID[itemID];
                else
                    return convertOpenKH[seedgenItemID[itemID]];
            }
            else
                return "Unknown";
        }

        public Dictionary<int, string> itemCodes = new Dictionary<int, string>
        {
            {21, "Fire"},
            {22, "Blizzard"},
            {23, "Thunder"},
            {24, "Cure"},
            {25, "Ukulele"},
            {26, "Valor"},
            {89, "Valor"}, //Dummy (Seedgen 3.0.1)
            {27, "Wisdom"},
            {29, "Final"},
            {115, "Final"}, //Dummy (Seedgen 3.0.1)
            {31, "Master"},
            {32, "TornPage"},
            {87, "Magnet"},
            {88, "Reflect"},
            {159, "Lamp"},
            {160, "Feather"},
            {226, "Report1"},
            {227, "Report2"},
            {228, "Report3"},
            {229, "Report4"},
            {230, "Report5"},
            {231, "Report6"},
            {232, "Report7"},
            {233, "Report8"},
            {234, "Report9" },
            {235, "Report10"},
            {236, "Report11"},
            {237, "Report12"},
            {238, "Report13"},
            {383, "Baseball"},
            {415, "SecondChance"},
            {416, "OnceMore"},
            {524, "PromiseCharm"},
            {563, "Limit"},
            {593, "Connection"},
            {594, "Nonexistence"},
            {595, "Peace"},
            {54, "AuronWep"},
            {55, "MulanWep"},
            {59, "BeastWep"},
            {60, "JackWep"},
            {61, "SimbaWep"},
            {62, "SparrowWep"},
            {72, "AladdinWep"},
            {74, "TronWep"},
            {369, "MembershipCard"},
            {375, "IceCream"},
            //{376, "Picture"},
            {30, "Anti"},
            {537, "HadesCup"},
            {370, "OlympusStone"},
            {462, "UnknownDisk"},
            {362, "MunnyPouch1"},
            {535, "MunnyPouch2"},
            {73, "RikuWep"},
            {460, "KingsLetter"},
            {368, "Sketches"},
            {0x02A, "ChestTT"},
            {0x1F2, "ChestSTT"},
            {0x1EE, "ChestHB"},
            {0x220, "ChestCoR"},
            {0x1EC, "ChestAG"},
            {0x1EA, "ChestBC"},
            {0x1E5, "ChestDC"},
            {0x1ED, "ChestHT"},
            {0x1E1, "ChestLoD"},
            {0x1E4, "ChestOC"},
            {0x1E7, "ChestPL"},
            {0x1E6, "ChestPR"},
            {0x1E8, "ChestSP"},
            {0x21F, "ChestTWTNW"},
            {0x1EF, "ChestHAW"}
        };

        public static Dictionary<int, string> seedgenItemID = new Dictionary<int, string>
        {
            {021, "Fire Element"},
            {022, "Blizzard Element"},
            {023, "Thunder Element"},
            {024, "Cure Element"},
            {025, "Ukulele Charm (Stitch)"},
            {026, "Valor Form"},
            {089, "Valor Form"}, //Dummy (Seedgen 3.0.1)
            {027, "Wisdom Form"},
            {029, "Final Form"},
            {115, "Final Form"}, //Dummy (Seedgen 3.0.1)
            {031, "Master Form"},
            {032, "Torn Pages"},
            {087, "Magnet Element"},
            {088, "Reflect Element"},
            {159, "Lamp Charm (Genie)"},
            {160, "Feather Charm (Peter Pan)"},
            {226, "Secret Ansem's Report 1"},
            {227, "Secret Ansem's Report 2"},
            {228, "Secret Ansem's Report 3"},
            {229, "Secret Ansem's Report 4"},
            {230, "Secret Ansem's Report 5"},
            {231, "Secret Ansem's Report 6"},
            {232, "Secret Ansem's Report 7"},
            {233, "Secret Ansem's Report 8"},
            {234, "Secret Ansem's Report 9" },
            {235, "Secret Ansem's Report 10"},
            {236, "Secret Ansem's Report 11"},
            {237, "Secret Ansem's Report 12"},
            {238, "Secret Ansem's Report 13"},
            {383, "Baseball Charm (Chicken Little)"},
            {415, "Second Chance"},
            {416, "Once More"},
            {524, "PromiseCharm"},
            {563, "Limit Form"},
            {593, "Proof of Connection"},
            {594, "Proof of Nonexistence"},
            {595, "Proof of Peace"},
            {054, "Battlefields of War (Auron)"},
            {055, "Sword of the Ancestor (Mulan)"},
            {059, "Beast's Claw (Beast)"},
            {060, "Bone Fist (Jack Skellington)"},
            {061, "Proud Fang (Simba)"},
            {062, "Skill and Crossbones (Jack Sparrow)"},
            {072, "Scimitar (Aladdin)"},
            {074, "Identity Disk (Tron)"},
            {369, "Membership Card"},
            {375, "Ice Cream"},
            {030, "Anti-Form"},
            {537, "Hades Cup Trophy"},
            {370, "Olympus Stone"},
            {462, "Unknown Disk"},
            {362, "Munny Pouch"},
            {535, "Munny Pouch"},
            {073, "Way to the Dawn (Riku)"},
            {460, "Disney Castle Key"},
            {368, "Namine's Sketches"},
            {0x02A, "Oathkeeper"},
            {0x1F2, "Bond of Flame"},
            {0x1EE, "Sleeping Lion"},
            {0x220, "Winner's Proof"},
            {0x1EC, "Wishing Lamp"},
            {0x1EA, "Rumbling Rose"},
            {0x1E5, "Monochrome"},
            {0x1ED, "Decisive Pumpkin"},
            {0x1E1, "Hidden Dragon"},
            {0x1E4, "Hero's Crest"},
            {0x1E7, "Circle of Life"},
            {0x1E6, "Follow the Wind"},
            {0x1E8, "Photon Debugger"},
            {0x21F, "Two Become One"},
            {0x1EF, "Sweet Memories"}
        };

        //Convert seed gen item names to tracker internal names
        public static string ConvertSeedGenName(string name)
        {
            if (convertOpenKH.ContainsKey(name))
                return convertOpenKH[name];
            else
                return "Unknown";
        }

        public static Dictionary<string, string> convertOpenKH = new Dictionary<string, string>()
        {
            //worlds
            {"Level", "SorasHeart" },
            {"Form Levels", "DriveForms" },
            {"Simulated Twilight Town", "SimulatedTwilightTown" },
            {"Twilight Town", "TwilightTown" },
            {"Hollow Bastion", "HollowBastion" },
            {"Beast's Castle", "BeastsCastle" },
            {"Olympus Coliseum", "OlympusColiseum" },
            {"Agrabah", "Agrabah" },
            {"Land of Dragons", "LandofDragons" },
            {"Hundred Acre Wood", "HundredAcreWood" },
            {"Pride Lands", "PrideLands" },
            {"Disney Castle / Timeless River", "DisneyCastle" },
            {"Halloween Town", "HalloweenTown" },
            {"Port Royal", "PortRoyal" },
            {"Space Paranoids", "SpaceParanoids" },
            {"The World That Never Was", "TWTNW" },
            {"Atlantica", "Atlantica" },
            {"Garden of Assemblage", "GoA"},
            {"", "GoA"},
            {"Critical Bonuses", "GoA"},
            {"Creations", "PuzzSynth"},
            {"Empty", "Empty"},
            //items
            {"Proof of Connection", "Connection" },
            {"Proof of Nonexistence", "Nonexistence" },
            {"Proof of Peace", "Peace" },
            {"PromiseCharm", "PromiseCharm" },
            {"Valor Form", "Valor" },
            {"Wisdom Form", "Wisdom" },
            {"Limit Form", "Limit" },
            {"Master Form", "Master" },
            {"Final Form", "Final" },
            {"Fire Element", "Fire" },
            {"Blizzard Element", "Blizzard" },
            {"Thunder Element", "Thunder" },
            {"Cure Element", "Cure" },
            {"Magnet Element", "Magnet" },
            {"Reflect Element", "Reflect" },
            {"Ukulele Charm (Stitch)", "Ukulele" },
            {"Baseball Charm (Chicken Little)", "Baseball" },
            {"Lamp Charm (Genie)", "Lamp" },
            {"Feather Charm (Peter Pan)", "Feather" },
            {"Torn Pages", "TornPage" },
            {"Second Chance", "SecondChance" },
            {"Once More", "OnceMore" },
            {"Secret Ansem's Report 1", "Report1"},
            {"Secret Ansem's Report 2", "Report2"},
            {"Secret Ansem's Report 3", "Report3"},
            {"Secret Ansem's Report 4", "Report4"},
            {"Secret Ansem's Report 5", "Report5"},
            {"Secret Ansem's Report 6", "Report6"},
            {"Secret Ansem's Report 7", "Report7"},
            {"Secret Ansem's Report 8", "Report8"},
            {"Secret Ansem's Report 9", "Report9"},
            {"Secret Ansem's Report 10", "Report10"},
            {"Secret Ansem's Report 11", "Report11"},
            {"Secret Ansem's Report 12", "Report12"},
            {"Secret Ansem's Report 13", "Report13"},
            {"Secret Ansem's Report 14", "Report14"},
            {"Secret Ansem's Report 15", "Report15"},
            {"Secret Ansem's Report 16", "Report16"},
            {"Battlefields of War (Auron)", "AuronWep"},
            {"Sword of the Ancestor (Mulan)", "MulanWep"},
            {"Beast's Claw (Beast)", "BeastWep"},
            {"Bone Fist (Jack Skellington)", "JackWep"},
            {"Proud Fang (Simba)", "SimbaWep"},
            {"Skill and Crossbones (Jack Sparrow)", "SparrowWep"},
            {"Scimitar (Aladdin)", "AladdinWep"},
            {"Identity Disk (Tron)", "TronWep"},
            {"Membership Card", "MembershipCard"},
            {"Ice Cream", "IceCream"},
            {"Anti-Form", "Anti"},
            {"Hades Cup Trophy", "HadesCup"},
            {"Olympus Stone", "OlympusStone"},
            {"Unknown Disk", "UnknownDisk"},
            {"Munny Pouch", "MunnyPouch" },
            {"Way to the Dawn (Riku)", "RikuWep"},
            {"Disney Castle Key", "KingsLetter"},
            {"Namine's Sketches", "Sketches"},
            {"Oathkeeper", "ChestTT"},
            {"Bond of Flame", "ChestSTT"},
            {"Sleeping Lion", "ChestHB"},
            {"Winner's Proof", "ChestCoR"},
            {"Wishing Lamp", "ChestAG"},
            {"Rumbling Rose", "ChestBC"},
            {"Monochrome", "ChestDC"},
            {"Decisive Pumpkin", "ChestHT"},
            {"Hidden Dragon", "ChestLoD"},
            {"Hero's Crest", "ChestOC"},
            {"Circle of Life", "ChestPL"},
            {"Follow the Wind", "ChestPR"},
            {"Photon Debugger", "ChestSP"},
            {"Two Become One", "ChestTWTNW"},
            {"Sweet Memories", "ChestHAW"},
        };

        //Convert some item names to something else shorter
        public static string FindShortName(string input, bool shorter = false)
        {
            string name = input;

            if (shorter && shorterNames.ContainsKey(name))
                return shorterNames[name];

            if (shortNames.ContainsKey(name))
                return shortNames[name];

            return name;
        }

        public static Dictionary<string, string> shortNames = new Dictionary<string, string>()
        {
            {"Secret Ansem's Report 1", "Ansem's Report"},
            {"Secret Ansem's Report 2", "Ansem's Report"},
            {"Secret Ansem's Report 3", "Ansem's Report"},
            {"Secret Ansem's Report 4", "Ansem's Report"},
            {"Secret Ansem's Report 5", "Ansem's Report"},
            {"Secret Ansem's Report 6", "Ansem's Report"},
            {"Secret Ansem's Report 7", "Ansem's Report"},
            {"Secret Ansem's Report 8", "Ansem's Report"},
            {"Secret Ansem's Report 9", "Ansem's Report"},
            {"Secret Ansem's Report 10", "Ansem's Report"},
            {"Secret Ansem's Report 11", "Ansem's Report"},
            {"Secret Ansem's Report 12", "Ansem's Report"},
            {"Secret Ansem's Report 13", "Ansem's Report"},
            {"Baseball Charm (Chicken Little)", "Baseball Charm"},
            {"Lamp Charm (Genie)", "Lamp Charm"},
            {"Ukulele Charm (Stitch)", "Ukulele Charm"},
            {"Feather Charm (Peter Pan)", "Feather Charm"},
            {"PromiseCharm", "Promise Charm"},
            {"Battlefields of War (Auron)", "Battlefields of War"},
            {"Sword of the Ancestor (Mulan)", "Sword of the Ancestor"},
            {"Beast's Claw (Beast)", "Beast's Claw"},
            {"Bone Fist (Jack Skellington)", "Bone Fist"},
            {"Proud Fang (Simba)", "Proud Fang"},
            {"Skill and Crossbones (Jack Sparrow)", "Skill and Crossbones"},
            {"Scimitar (Aladdin)", "Scimitar"},
            {"Identity Disk (Tron)", "Identity Disk"},
            {"Way to the Dawn (Riku)", "Way to the Dawn"},
            {"Munny Pouch (Olette)", "Munny Pouch"},
            {"Munny Pouch (Mickey)", "Munny Pouch"},
            {"Sora's Heart", "Levels" },
            {"Drive Forms", "Drives" },
            {"Simulated Twilight Town", "STT" },
            {"Twilight Town", "TT" },
            {"Hollow Bastion", "HB" },
            {"Beast's Castle", "BC" },
            {"Olympus Coliseum", "OC" },
            {"Agrabah", "AG" },
            {"Land of Dragons", "LoD" },
            {"Hundred Acre Wood", "100AW" },
            {"Pride Lands", "PL" },
            {"Disney Castle", "DC" },
            {"Halloween Town", "HT" },
            {"Port Royal", "PR" },
            {"Space Paranoids", "SP" },
            {"Atlantica", "AT" }
        };

        public static Dictionary<string, string> shorterNames = new Dictionary<string, string>()
        {
            {"Sora's Heart", "Levels" },
            {"Drive Forms", "Drives" },
            {"Simulated Twilight Town", "STT" },
            {"Twilight Town", "TT" },
            {"Hollow Bastion", "HB" },
            {"Beast's Castle", "BC" },
            {"Olympus Coliseum", "OC" },
            {"Agrabah", "AG" },
            {"Land of Dragons", "LoD" },
            {"Hundred Acre Wood", "100AW" },
            {"Pride Lands", "PL" },
            {"Disney Castle", "DC" },
            {"Halloween Town", "HT" },
            {"Port Royal", "PR" },
            {"Space Paranoids", "SP" },
            {"Atlantica", "AT" }
        };

        //Find the item type an Important Check belongs to
        public static string FindItemType(string name)
        {
            if (itemTypes.Keys.Contains(name))
                return itemTypes[name];
            else
                return "Unknown";
        }

        public static Dictionary<string, string> itemTypes = new Dictionary<string, string>()
        {
            {"Report1", "report"},
            {"Report2", "report"},
            {"Report3", "report"},
            {"Report4", "report"},
            {"Report5", "report"},
            {"Report6", "report"},
            {"Report7", "report"},
            {"Report8", "report"},
            {"Report9", "report"},
            {"Report10", "report"},
            {"Report11", "report"},
            {"Report12", "report"},
            {"Report13", "report"},
            {"Fire", "magic"},
            {"Fire1", "magic"},
            {"Fire2", "magic"},
            {"Fire3", "magic"},
            {"Blizzard", "magic"},
            {"Blizzard1", "magic"},
            {"Blizzard2", "magic"},
            {"Blizzard3", "magic"},
            {"Thunder", "magic"},
            {"Thunder1", "magic"},
            {"Thunder2", "magic"},
            {"Thunder3", "magic"},
            {"Cure", "magic"},
            {"Cure1", "magic"},
            {"Cure2", "magic"},
            {"Cure3", "magic"},
            {"Reflect", "magic"},
            {"Reflect1", "magic"},
            {"Reflect2", "magic"},
            {"Reflect3", "magic"},
            {"Magnet", "magic"},
            {"Magnet1", "magic"},
            {"Magnet2", "magic"},
            {"Magnet3", "magic"},
            {"Valor", "form"},
            {"Wisdom", "form"},
            {"Limit", "form"},
            {"Master", "form"},
            {"Final", "form"},
            {"OnceMore", "ability"},
            {"SecondChance", "ability"},
            {"TornPage", "page"},
            {"TornPage1", "page"},
            {"TornPage2", "page"},
            {"TornPage3", "page"},
            {"TornPage4", "page"},
            {"TornPage5", "page"},
            {"Baseball", "summon"},
            {"Lamp", "summon"},
            {"Ukulele", "summon"},
            {"Feather", "summon"},
            {"Connection", "proof"},
            {"Nonexistence", "proof"},
            {"Peace", "proof"},
            {"PromiseCharm", "proof"},
            {"AuronWep", "visit"},
            {"MulanWep", "visit"},
            {"BeastWep", "visit"},
            {"JackWep", "visit"},
            {"SimbaWep", "visit"},
            {"SparrowWep", "visit"},
            {"AladdinWep", "visit"},
            {"TronWep", "visit"},
            {"MembershipCard", "visit"},
            {"IceCream", "visit"},
            {"Picture", "visit"},
            {"Anti", "form"},
            {"HadesCup", "other"},
            {"OlympusStone", "other"},
            {"UnknownDisk", "other"},
            {"MunnyPouch", "other"},
            {"MunnyPouch1", "other"},
            {"MunnyPouch2", "other"},
            {"RikuWep", "visit"},
            {"KingsLetter", "visit"},
            {"AuronWep1", "visit"},
            {"AuronWep2", "visit"},
            {"MulanWep1", "visit"},
            {"MulanWep2", "visit"},
            {"BeastWep1", "visit"},
            {"BeastWep2", "visit"},
            {"JackWep1", "visit"},
            {"JackWep2", "visit"},
            {"SimbaWep1", "visit"},
            {"SimbaWep2", "visit"},
            {"SparrowWep1", "visit"},
            {"SparrowWep2", "visit"},
            {"AladdinWep1", "visit"},
            {"AladdinWep2", "visit"},
            {"TronWep1", "visit"},
            {"TronWep2", "visit"},
            {"MembershipCard1", "visit"},
            {"MembershipCard2", "visit"},
            {"IceCream1", "visit"},
            {"IceCream2", "visit"},
            {"IceCream3", "visit"},
            {"RikuWep1", "visit"},
            {"RikuWep2", "visit"},
            {"KingsLetter1", "visit"},
            {"KingsLetter2", "visit"},
            {"Sketches", "visit"},
            {"ChestTT", "keyblade"},
            {"ChestSTT", "keyblade"},
            {"ChestHB", "keyblade"},
            {"ChestCoR", "keyblade"},
            {"ChestAG", "keyblade"},
            {"ChestBC", "keyblade"},
            {"ChestDC", "keyblade"},
            {"ChestHT", "keyblade"},
            {"ChestLoD", "keyblade"},
            {"ChestOC", "keyblade"},
            {"ChestPL", "keyblade"},
            {"ChestPR", "keyblade"},
            {"ChestSP", "keyblade"},
            {"ChestTWTNW", "keyblade"},
            {"ChestHAW", "keyblade"},
            //ghost versions
            {"Ghost_Report1", "report"},
            {"Ghost_Report2", "report"},
            {"Ghost_Report3", "report"},
            {"Ghost_Report4", "report"},
            {"Ghost_Report5", "report"},
            {"Ghost_Report6", "report"},
            {"Ghost_Report7", "report"},
            {"Ghost_Report8", "report"},
            {"Ghost_Report9", "report"},
            {"Ghost_Report10", "report"},
            {"Ghost_Report11", "report"},
            {"Ghost_Report12", "report"},
            {"Ghost_Report13", "report"},
            {"Ghost_Fire1", "magic"},
            {"Ghost_Fire2", "magic"},
            {"Ghost_Fire3", "magic"},
            {"Ghost_Blizzard1", "magic"},
            {"Ghost_Blizzard2", "magic"},
            {"Ghost_Blizzard3", "magic"},
            {"Ghost_Thunder1", "magic"},
            {"Ghost_Thunder2", "magic"},
            {"Ghost_Thunder3", "magic"},
            {"Ghost_Cure1", "magic"},
            {"Ghost_Cure2", "magic"},
            {"Ghost_Cure3", "magic"},
            {"Ghost_Reflect1", "magic"},
            {"Ghost_Reflect2", "magic"},
            {"Ghost_Reflect3", "magic"},
            {"Ghost_Magnet1", "magic"},
            {"Ghost_Magnet2", "magic"},
            {"Ghost_Magnet3", "magic"},
            {"Ghost_Valor", "form"},
            {"Ghost_Wisdom", "form"},
            {"Ghost_Limit", "form"},
            {"Ghost_Master", "form"},
            {"Ghost_Final", "form"},
            {"Ghost_OnceMore", "ability"},
            {"Ghost_SecondChance", "ability"},
            {"Ghost_TornPage1", "page"},
            {"Ghost_TornPage2", "page"},
            {"Ghost_TornPage3", "page"},
            {"Ghost_TornPage4", "page"},
            {"Ghost_TornPage5", "page"},
            {"Ghost_Baseball", "summon"},
            {"Ghost_Lamp", "summon"},
            {"Ghost_Ukulele", "summon"},
            {"Ghost_Feather", "summon"},
            {"Ghost_Connection", "proof"},
            {"Ghost_Nonexistence", "proof"},
            {"Ghost_Peace", "proof"},
            {"Ghost_PromiseCharm", "proof"},
            {"Ghost_Anti", "form"},
            {"Ghost_HadesCup", "other"},
            {"Ghost_OlympusStone", "other"},
            {"Ghost_UnknownDisk", "other"},
            {"Ghost_MunnyPouch1", "other"},
            {"Ghost_MunnyPouch2", "other"},
            {"Ghost_AuronWep1", "visit"},
            {"Ghost_AuronWep2", "visit"},
            {"Ghost_MulanWep1", "visit"},
            {"Ghost_MulanWep2", "visit"},
            {"Ghost_BeastWep1", "visit"},
            {"Ghost_BeastWep2", "visit"},
            {"Ghost_JackWep1", "visit"},
            {"Ghost_JackWep2", "visit"},
            {"Ghost_SimbaWep1", "visit"},
            {"Ghost_SimbaWep2", "visit"},
            {"Ghost_SparrowWep1", "visit"},
            {"Ghost_SparrowWep2", "visit"},
            {"Ghost_AladdinWep1", "visit"},
            {"Ghost_AladdinWep2", "visit"},
            {"Ghost_TronWep1", "visit"},
            {"Ghost_TronWep2", "visit"},
            {"Ghost_MembershipCard1", "visit"},
            {"Ghost_MembershipCard2", "visit"},
            {"Ghost_IceCream1", "visit"},
            {"Ghost_IceCream2", "visit"},
            {"Ghost_IceCream3", "visit"},
            {"Ghost_RikuWep1", "visit"},
            {"Ghost_RikuWep2", "visit"},
            {"Ghost_KingsLetter1", "visit"},
            {"Ghost_KingsLetter2", "visit"},
            {"Ghost_Sketches", "visit"},
            {"Ghost_ChestTT", "keyblade"},
            {"Ghost_ChestSTT", "keyblade"},
            {"Ghost_ChestHB", "keyblade"},
            {"Ghost_ChestCoR", "keyblade"},
            {"Ghost_ChestAG", "keyblade"},
            {"Ghost_ChestBC", "keyblade"},
            {"Ghost_ChestDC", "keyblade"},
            {"Ghost_ChestHT", "keyblade"},
            {"Ghost_ChestLoD", "keyblade"},
            {"Ghost_ChestOC", "keyblade"},
            {"Ghost_ChestPL", "keyblade"},
            {"Ghost_ChestPR", "keyblade"},
            {"Ghost_ChestSP", "keyblade"},
            {"Ghost_ChestTWTNW", "keyblade"},
            {"Ghost_ChestHAW", "keyblade"},
            //seedgen names
            {"Fire Element", "magic"},
            {"Blizzard Element", "magic"},
            {"Thunder Element", "magic"},
            {"Cure Element", "magic"},
            {"Magnet Element", "magic"},
            {"Reflect Element", "magic"},
            {"Ukulele Charm (Stitch)", "summon"},
            {"Lamp Charm (Genie)", "summon"},
            {"Feather Charm (Peter Pan)", "summon"},
            {"Baseball Charm (Chicken Little)", "summon"},
            {"Valor Form", "form"},
            {"Wisdom Form", "form"},
            {"Final Form", "form"},
            {"Master Form", "form"},
            {"Limit Form", "form"},
            {"Second Chance", "ability"},
            {"Once More", "ability"},
            {"Promise Charm", "proof"},
            {"Proof of Connection", "proof"},
            {"Proof of Nonexistence", "proof"},
            {"Proof of Peace", "proof"},
            {"Torn Pages", "page"},
            {"Secret Ansem's Report 1", "report"},
            {"Secret Ansem's Report 2", "report"},
            {"Secret Ansem's Report 3", "report"},
            {"Secret Ansem's Report 4", "report"},
            {"Secret Ansem's Report 5", "report"},
            {"Secret Ansem's Report 6", "report"},
            {"Secret Ansem's Report 7", "report"},
            {"Secret Ansem's Report 8", "report"},
            {"Secret Ansem's Report 9", "report"},
            {"Secret Ansem's Report 10", "report"},
            {"Secret Ansem's Report 11", "report"},
            {"Secret Ansem's Report 12", "report"},
            {"Secret Ansem's Report 13", "report"},
            {"Battlefields of War (Auron)", "visit"},
            {"Sword of the Ancestor (Mulan)", "visit"},
            {"Beast's Claw (Beast)", "visit"},
            {"Bone Fist (Jack Skellington)", "visit"},
            {"Proud Fang (Simba)", "visit"},
            {"Skill and Crossbones (Jack Sparrow)", "visit"},
            {"Scimitar (Aladdin)", "visit"},
            {"Identity Disk (Tron)", "visit"},
            {"Membership Card", "visit"},
            {"Ice Cream", "visit"},
            {"Anti-Form", "form"},
            {"Hades Cup Trophy", "other"},
            {"Olympus Stone", "other"},
            {"Unknown Disk", "other"},
            {"Munny Pouch", "other"},
            {"Way to the Dawn (Riku)", "visit"},
            {"Disney Castle Key", "visit"},
            {"Namine's Sketches", "visit"},
            {"Oathkeeper", "keyblade"},
            {"Bond of Flame", "keyblade"},
            {"Sleeping Lion", "keyblade"},
            {"Winner's Proof", "keyblade"},
            {"Wishing Lamp", "keyblade"},
            {"Rumbling Rose", "keyblade"},
            {"Monochrome", "keyblade"},
            {"Decisive Pumpkin", "keyblade"},
            {"Hidden Dragon", "keyblade"},
            {"Hero's Crest", "keyblade"},
            {"Circle of Life", "keyblade"},
            {"Follow the Wind", "keyblade"},
            {"Photon Debugger", "keyblade"},
            {"Two Become One", "keyblade"},
            {"Sweet Memories", "keyblade"}
        };

        //Get what color text should be for hint text
        public static string GetTextColor(string name)
        {
            if (getColors.Keys.Contains(name))
                return getColors[name];
            else if (name.EndsWith("important checks"))
                return "Gold";
            else
                return "DefWhite";
        }

        public static Dictionary<string, string> getColors = new Dictionary<string, string>()
        {
            {"Sora's Heart", "Pink" },
            {"Drive Forms", "Gold" },
            {"Simulated Twilight Town", "WhiteBlue" },
            {"Twilight Town", "Orange" },
            {"Hollow Bastion", "Pink" },
            {"Beast's Castle", "Pink" },
            {"Olympus Coliseum", "Green" },
            {"Agrabah", "Gold" },
            {"Land of Dragons", "Red" },
            {"Hundred Acre Wood", "Gold" },
            {"Pride Lands", "Red" },
            {"Disney Castle", "LightBlue" },
            {"Halloween Town", "Purple" },
            {"Port Royal", "DarkBlue" },
            {"Space Paranoids", "DarkBlue" },
            {"TWTNW", "White" },
            {"Atlantica", "LightBlue" },
            {"Creations", "Pink"},
            {"GoA", "WhiteBlue"},
            {"Secret Ansem's Report 1", "White"},
            {"Secret Ansem's Report 2", "White"},
            {"Secret Ansem's Report 3", "White"},
            {"Secret Ansem's Report 4", "White"},
            {"Secret Ansem's Report 5", "White"},
            {"Secret Ansem's Report 6", "White"},
            {"Secret Ansem's Report 7", "White"},
            {"Secret Ansem's Report 8", "White"},
            {"Secret Ansem's Report 9", "White"},
            {"Secret Ansem's Report 10", "White"},
            {"Secret Ansem's Report 11", "White"},
            {"Secret Ansem's Report 12", "White"},
            {"Secret Ansem's Report 13", "White"},
            {"Valor Form", "Red"},
            {"Wisdom Form", "LightBlue"},
            {"Limit Form", "Orange"},
            {"Master Form", "Gold"},
            {"Final Form", "White"},
            {"Anti-Form", "DarkBlue"},
            {"Once More", "LightBlue"},
            {"Second Chance", "Green"},
            {"Baseball Charm", "Gold"},
            {"Lamp Charm", "Purple"},
            {"Ukulele Charm", "LightBlue"},
            {"Feather Charm", "Red"},
            {"Proof of Connection", "OffWhite"},
            {"Proof of Nonexistence", "OffWhite"},
            {"Proof of Peace", "OffWhite"},
            {"Promise Charm", "Pink"},
            {"Battlefields of War", "Green"},
            {"Sword of the Ancestor", "Orange"},
            {"Beast's Claw", "Pink"},
            {"Bone Fist", "Purple"},
            {"Proud Fang", "Red"},
            {"Skill and Crossbones", "DarkBlue"},
            {"Scimitar", "Gold"},
            {"Identity Disk", "DarkBlue"},
            {"Membership Card", "Purple"},
            {"Ice Cream", "LightBlue"},
            {"Picture", "Orange"},
            {"Hades Cup Trophy", "DarkBlue"},
            {"Olympus Stone", "Gold"},
            {"Unknown Disk", "White"},
            {"Munny Pouch", "Red"},
            {"Fire Element", "Orange" },
            {"Blizzard Element", "DarkBlue" },
            {"Thunder Element", "Gold" },
            {"Cure Element", "Green" },
            {"Magnet Element", "Pink" },
            {"Reflect Element", "WhiteBlue" },
            {"Torn Pages", "Gold" },
            {"Way to the Dawn (Riku)", "White"},
            {"Disney Castle Key", "LightBlue"},
            {"Namine's Sketches", "WhiteBlue"},
            {"Oathkeeper", "Orange"},
            {"Bond of Flame", "WhiteBlue"},
            {"Sleeping Lion", "Pink"},
            {"Winner's Proof", "DarkBlue"},
            {"Wishing Lamp", "Gold"},
            {"Rumbling Rose", "Pink"},
            {"Monochrome", "LightBlue"},
            {"Decisive Pumpkin", "Purple"},
            {"Hidden Dragon", "Red"},
            {"Hero's Crest", "Green"},
            {"Circle of Life", "Red"},
            {"Follow the Wind", "DarkBlue"},
            {"Photon Debugger", "DarkBlue"},
            {"Two Become One", "White"},
            {"Sweet Memories", "Gold"}
        };

        //Convert the seed icon image hash into numbers 
        public static Dictionary<string, int> HashInt = new Dictionary<string, int>
        {
            {"ability-unequip", 1},
            {"accessory", 2},
            {"ai-mode-frequent", 3},
            {"ai-mode-moderate", 4},
            {"ai-mode-rare", 5},
            {"ai-settings", 6},
            {"armor", 7},
            {"button-circle", 8},
            {"button-cross", 9},
            {"button-l1", 10},
            {"button-l2", 11},
            {"button-r1", 12},
            {"button-r2", 13},
            {"button-square", 14},
            {"button-triangle", 15},
            {"exclamation-mark", 16},
            {"form", 17},
            {"gumi-block", 18},
            {"gumi-blueprint", 19},
            {"gumi-brush", 20},
            {"gumi-gear", 21},
            {"gumi-ship", 22},
            {"item-consumable", 23},
            {"item-key", 24},
            {"item-tent", 25},
            {"magic", 26},
            {"material", 27},
            {"party", 28},
            {"question-mark", 29},
            {"rank-a", 30},
            {"rank-b", 31},
            {"rank-c", 32},
            {"rank-s", 33},
            {"weapon-keyblade", 34},
            {"weapon-shield", 35},
            {"weapon-staff", 36}
        };

        //Resource names for GridTracker
        public static List<string> gridAssetList = new List<string>()
        {
            //Reports
            {"Report1"},
            {"Report2"},
            {"Report3"},
            {"Report4"},
            {"Report5"},
            {"Report6"},
            {"Report7"},
            {"Report8"},
            {"Report9"},
            {"Report10"},
            {"Report11"},
            {"Report12"},
            {"Report13"},
            //TornPages
            {"GridTornPage1"},
            {"GridTornPage2"},
            {"GridTornPage3"},
            {"GridTornPage4"},
            {"GridTornPage5"},
            //Drive Forms
            {"Valor"},
            {"Valor2"},
            {"Valor3"},
            {"Valor4"},
            {"Valor5"},
            {"Valor6"},
            {"Valor7"},
            {"Wisdom"},
            {"Wisdom2"},
            {"Wisdom3"},
            {"Wisdom4"},
            {"Wisdom5"},
            {"Wisdom6"},
            {"Wisdom7"},
            {"Limit"},
            {"Limit2"},
            {"Limit3"},
            {"Limit4"},
            {"Limit5"},
            {"Limit6"},
            {"Limit7"},
            {"Master"},
            {"Master2"},
            {"Master3"},
            {"Master4"},
            {"Master5"},
            {"Master6"},
            {"Master7"},
            {"Final"},
            {"Final2"},
            {"Final3"},
            {"Final4"},
            {"Final5"},
            {"Final6"},
            {"Final7"},
            {"Anti"},
            //Summons
            {"Lamp"},
            {"Ukulele"},
            {"Baseball"},
            {"Feather"},
            //Proofs
            {"Nonexistence"},
            {"Connection"},
            {"Peace"},
            {"PromiseCharm"},
            //Abilities
            {"OnceMore"},
            {"SecondChance"},
            //Visit Locks
            {"Sketches"},
            {"RikuWep1"},
            {"RikuWep2"},
            {"KingsLetter1"},
            {"KingsLetter2"},
            {"AuronWep1"},
            {"AuronWep2"},
            {"MulanWep1"},
            {"MulanWep2"},
            {"BeastWep1"},
            {"BeastWep2"},
            {"JackWep1"},
            {"JackWep2"},
            {"SimbaWep1"},
            {"SimbaWep2"},
            {"SparrowWep1"},
            {"SparrowWep2"},
            {"AladdinWep1"},
            {"AladdinWep2"},
            {"TronWep1"},
            {"TronWep2"},
            {"MembershipCard1"},
            {"MembershipCard2"},
            {"IceCream1"},
            {"IceCream2"},
            {"IceCream3"},
            //Extra
            {"HadesCup"},
            {"OlympusStone"},
            {"UnknownDisk"},
            {"GridMunnyPouch1"},
            {"GridMunnyPouch2"},
            //Chest Lock
            {"ChestAG"},
            {"ChestBC"},
            {"ChestDC"},
            {"ChestHT"},
            {"ChestOC"},
            {"ChestPL"},
            {"ChestPR"},
            {"ChestSP"},
            {"ChestTT"},
            {"ChestHB"},
            {"ChestLoD"},
            {"ChestCoR"},
            {"ChestSTT"},
            {"ChestHAW"},
            {"ChestTWTNW"},
            //Magic
            {"GridFire1"},
            {"GridFire2"},
            {"GridFire3"},
            {"GridBlizzard1"},
            {"GridBlizzard2"},
            {"GridBlizzard3"},
            {"GridThunder1"},
            {"GridThunder2"},
            {"GridThunder3"},
            {"GridCure1"},
            {"GridCure2"},
            {"GridCure3"},
            {"GridReflect1"},
            {"GridReflect2"},
            {"GridReflect3"},
            {"GridMagnet1"},
            {"GridMagnet2"},
            {"GridMagnet3"},
            //Growth
            {"HighJump1"},
            {"HighJump2"},
            {"HighJump3"},
            {"HighJump4"},
            {"QuickRun1"},
            {"QuickRun2"},
            {"QuickRun3"},
            {"QuickRun4"},
            {"DodgeRoll1"},
            {"DodgeRoll2"},
            {"DodgeRoll3"},
            {"DodgeRoll4"},
            {"AerialDodge1"},
            {"AerialDodge2"},
            {"AerialDodge3"},
            {"AerialDodge4"},
            {"Glide1"},
            {"Glide2"},
            {"Glide3"},
            {"Glide4"},
            //100 Acre Wood
            {"Piglet"},
            {"Rabbit"},
            {"Kanga"},
            {"SpookyCave"},
            {"StarryHill"},
            //Agrabah
            {"Abu"},
            {"Chasm"},
            {"TreasureRoom"},
            {"Lords"},
            {"GenieJafar"},
            //Atlantica
            {"Tutorial"},
            {"Ursula"},
            {"NewDay"},
            //Beasts Castle
            {"Thresholder"},
            {"Beast"},
            {"DarkThorn"},
            {"Dragoons"},
            {"Xaldin"},
            //Disney Castle
            {"Minnie"},
            {"OldPete"},
            {"Windows"},
            {"BoatPete"},
            {"DCPete"},
            //Halloween Town
            {"CandyCaneLane"},
            {"PrisonKeeper"},
            {"OogieBoogie"},
            {"Children"},
            {"Presents"},
            {"Experiment"},
            //Hollow Bastion
            {"Bailey"},
            {"AnsemStudy"},
            {"Corridor"},
            {"Dancers"},
            {"HBDemyx"},
            {"FinalFantasy"},
            {"1000Heartless"},
            //Cavern of Rememberance
            {"Fight1"},
            {"Fight2"},
            {"Transport"},
            //Land of Dragons
            {"Missions"},
            {"Mountain"},
            {"Cave"},
            {"Summit"},
            {"ShanYu"},
            {"ThroneRoom"},
            {"StormRider"},
            //Olympus Coliseum
            {"Cerberus"},
            {"Urns"},
            {"OCDemyx"},
            {"OCPete"},
            {"Hydra"},
            {"AuronStatue"},
            {"Hades"},
            //Port Royal
            {"Town"},
            {"1Minute"},
            {"Medallions"},
            {"Barrels"},
            {"Barbossa"},
            {"GrimReaper1"},
            {"Gambler"},
            {"GrimReaper"},
            //Pride Lands
            {"Simba"},
            {"Hyenas1"},
            {"Scar"},
            {"Hyenas2"},
            {"GroundShaker"},
            //Simulated Twilight Town
            {"Minigame"},
            {"TwilightThorn"},
            {"Axel1"},
            {"Struggle"},
            {"ComputerRoom"},
            {"Axel"},
            //Space Paranoids
            {"Screens"},
            {"HostileProgram"},
            {"SolarSailer"},
            {"Sark"},
            {"MCP"},
            //TWTNW
            {"Roxas"},
            {"Xigbar"},
            {"Luxord"},
            {"Saix"},
            {"Xemnas1"},
            //Twilight Town
            {"Station"},
            {"MysteriousTower"},
            {"Sandlot"},
            {"Mansion"},
            {"BetwixtAndBetween"},
            //Drive Forms
            //{"Drive2"},
            {"Drive3"},
            {"Drive4"},
            {"Drive5"},
            {"Drive6"},
            {"Drive7"},
            //Grid Tracker Uniques
            {"Grid7Drives"},
            {"GridDataAxel"},
            {"GridDataDemyx"},
            {"GridLarxene"},
            {"GridLarxeneData"},
            {"GridLexaeus"},
            {"GridLexaeusData"},
            {"GridLingeringWill"},
            {"GridDataLuxord"},
            {"GridMarluxia"},
            {"GridMarluxiaData"},
            {"GridDataRoxas"},
            {"GridDataSaix"},
            {"GridSephiroth"},
            {"GridDataXaldin"},
            {"GridDataXemnas"},
            {"GridFinalXemnas"},
            {"GridDataFinalXemnas"},
            {"GridDataXigbar"},
            {"GridVexen"},
            {"GridVexenData"},
            {"GridZexion"},
            {"GridZexionData"},
            {"GridArmoredXemnas1"},
            {"GridArmoredXemnas2"},
            {"GridCloud"},
            {"GridHayner"},
            {"GridHercules"},
            {"GridLeon"},
            {"GridRiku"},
            {"GridSeifer"},
            {"GridSetzer"},
            {"GridShadowStalker"},
            {"GridTifa"},
            {"GridVivi"},
            {"GridYuffie"},
            {"GridBlizzardLord"},
            {"GridVolcanoLord"},
        };

        //Bosses and Boss Rando
        public static string FindBossType(string name)
        {
            if (bossTypes.Keys.Contains(name))
                return bossTypes[name];
            else
                return "boss_other";
        }

        public static Dictionary<string, string> bossTypes = new Dictionary<string, string>()
        {
            {"Armor Xemnas I", "boss_other"},
            {"Armor Xemnas II", "boss_other"},
            {"Axel (Data)", "boss_datas"},
            {"Axel I", "boss_other"},
            {"Axel II", "boss_other"},
            {"Barbossa", "boss_other"},
            {"Blizzard Lord", "boss_other"},
            {"Blizzard Lord (Cups)", "boss_other"},
            {"Cerberus", "boss_other"},
            {"Cerberus (Cups)", "boss_other"},
            {"Cloud", "boss_other"},
            {"Cloud (1)", "boss_other"},
            {"Cloud (2)", "boss_other"},
            {"Dark Thorn", "boss_other"},
            {"Demyx", "boss_other"},
            {"Demyx (Data)", "boss_datas"},
            {"Grim Reaper I", "boss_other"},
            {"Grim Reaper II", "boss_other"},
            {"Hades Cups", "boss_other"},
            {"Hades II", "boss_other"},
            {"Hades II (1)", "boss_other"},
            {"Hayner", "boss_other"},
            {"Hercules", "boss_other"},
            {"Hostile Program", "boss_other"},
            {"Larxene", "boss_as"},
            {"Larxene (Data)", "boss_datas"},
            {"Leon", "boss_other"},
            {"Leon (1)", "boss_other"},
            {"Leon (2)", "boss_other"},
            {"Leon (3)", "boss_other"},
            {"Lexaeus", "boss_as"},
            {"Lexaeus (Data)", "boss_datas"},
            {"Luxord", "boss_other"},
            {"Luxord (Data)", "boss_datas"},
            {"Marluxia", "boss_as"},
            {"Marluxia (Data)", "boss_datas"},
            {"Past Pete", "boss_other"},
            {"Pete Cups", "boss_other"},
            {"Pete OC II", "boss_other"},
            {"Prison Keeper", "boss_other"},
            {"Roxas", "boss_other"},
            {"Roxas (Data)", "boss_datas"},
            {"Saix", "boss_other"},
            {"Saix (Data)", "boss_datas"},
            {"Sark", "boss_other"},
            {"Scar", "boss_other"},
            {"Seifer", "boss_other"},
            {"Seifer (1)", "boss_other"},
            {"Seifer (2)", "boss_other"},
            {"Seifer (3)", "boss_other"},
            {"Seifer (4)", "boss_other"},
            {"Sephiroth", "boss_sephi"},
            {"Setzer", "boss_other"},
            {"Shan-Yu", "boss_other"},
            {"Terra", "boss_terra"},
            {"The Beast", "boss_other"},
            {"The Experiment", "boss_other"},
            {"Thresholder", "boss_other"},
            {"Tifa", "boss_other"},
            {"Tifa (1)", "boss_other"},
            {"Tifa (2)", "boss_other"},
            {"Twilight Thorn", "boss_other"},
            {"Vexen", "boss_as"},
            {"Vexen (Data)", "boss_datas"},
            {"Vivi", "boss_other"},
            {"Volcano Lord", "boss_other"},
            {"Volcano Lord (Cups)", "boss_other"},
            {"Xaldin", "boss_other"},
            {"Xaldin (Data)", "boss_datas"},
            {"Xemnas", "boss_other"},
            {"Xemnas (Data)", "boss_datas"},
            {"Final Xemnas", "boss_other"},
            {"Final Xemnas (Data)", "boss_datas"},
            {"Xigbar", "boss_other"},
            {"Xigbar (Data)", "boss_datas"},
            {"Yuffie", "boss_other"},
            {"Yuffie (1)", "boss_other"},
            {"Yuffie (2)", "boss_other"},
            {"Yuffie (3)", "boss_other"},
            {"Zexion", "boss_as"},
            {"Zexion (Data)", "boss_datas"},
            {"Hydra", "boss_other"},
            {"Jafar", "boss_other"},
            {"Storm Rider", "boss_other"},
            {"Groundshaker", "boss_other"},
            {"Boat Pete", "boss_other"},
            {"Pete TR", "boss_other"},
            {"Oogie Boogie", "boss_other"},
            {"MCP", "boss_other"}
        };

        public static Dictionary<string, string> bossLocations = new Dictionary<string, string>()
        {
            //Orgmembers (AS)
            {"Marluxia", "DC"},
            {"Marluxia (Data)", "DC"},
            {"Lexaeus", "AG"},
            {"Lexaeus (Data)", "AG"},
            {"Larxene", "SP"},
            {"Larxene (Data)", "SP"},
            {"Vexen", "HT"},
            {"Vexen (Data)", "HT"},
            {"Zexion", "OC"},
            {"Zexion (Data)", "OC"},
            //Orgmembers (Normal)
            {"Armor Xemnas I", "TWTNW"},
            {"Armor Xemnas II", "TWTNW"},
            {"Final Xemnas", "TWTNW"},
            {"Final Xemnas (Data)", "TWTNW"},
            {"Axel (Data)", "TT"},
            {"Axel I", "STT"},
            {"Axel II", "STT"},
            {"Demyx", "HB"},
            {"Demyx (Data)", "HB"},
            {"Luxord", "TWTNW"},
            {"Luxord (Data)", "PR"},
            {"Roxas", "TWTNW"},
            {"Roxas (Data)", "STT"},
            {"Saix", "TWTNW"},
            {"Saix (Data)", "PL"},
            {"Xaldin", "BC"},
            {"Xaldin (Data)", "BC"},
            {"Xemnas", "TWTNW"},
            {"Xemnas (Data)", "TWTNW"},
            {"Xigbar", "TWTNW"},
            {"Xigbar (Data)", "LoD"},
            //
            {"Blizzard Lord", "AG"},
            {"Volcano Lord", "AG"},
            {"Jafar", "AG"},
            //
            {"Barbossa", "PR"},
            {"Grim Reaper I", "PR"},
            {"Grim Reaper II", "PR"},
            //
            {"Thresholder", "BC"},
            {"The Beast", "BC"},
            {"Shadow Stalker", "BC"},
            {"Dark Thorn", "BC"},
            //
            {"Hostile Program", "SP"},
            {"Sark", "SP"},
            {"MCP", "SP"},
            {"Past Pete", "DC"},
            {"Boat Pete", "DC"},
            {"Pete TR", "DC"},
            //
            {"Prison Keeper", "HT"},
            {"Oogie Boogie", "HT"},
            {"The Experiment", "HT"},
            //
            {"Shan-Yu", "LoD"},
            {"Riku", "LoD"},
            {"Storm Rider", "LoD"},
            //
            {"Scar", "PL"},
            {"Groundshaker", "PL"},
            //STT
            {"Twilight Thorn", "STT"},
            {"Hayner", "STT"},
            {"Vivi", "STT"},
            {"Setzer", "STT"},
            //
            {"Seifer", "STT"},
            {"Seifer (1)", "STT"},
            {"Seifer (2)", "STT"},
            {"Seifer (3)", "TT"},
            {"Seifer (4)", "TT"},
            //
            {"Sephiroth", "HB"},
            {"Terra", "DC"},
            //
            {"Hades I", "OC"},  //should probably skip this one for hinting and whatnot
            {"Hades Escape", "OC" }, //should probably skip this one for hinting and whatnot
            {"Cerberus", "OC"},
            {"Pete OC II", "OC"},
            {"Hydra", "OC"},
            {"Hades II", "OC"},
            {"Hades II (1)", "OC"},
            //Cups
            {"Blizzard Lord (Cups)", "OC"},
            {"Volcano Lord (Cups)", "OC"},
            {"Cerberus (Cups)", "OC"},
            {"Hercules", "OC"},
            {"Hades Cups", "OC"},
            {"Pete Cups", "OC"},
            {"Cloud", "OC"},
            {"Cloud (1)", "OC"},
            {"Cloud (2)", "OC"},
            {"Leon", "OC"},
            {"Leon (1)", "OC"},
            {"Leon (2)", "OC"},
            {"Leon (3)", "OC"},
            {"Tifa", "OC"},
            {"Tifa (1)", "OC"},
            {"Tifa (2)", "OC"},
            {"Yuffie", "OC"},
            {"Yuffie (1)", "OC"},
            {"Yuffie (2)", "OC"},
            {"Yuffie (3)", "OC"},
        };

        public static List<string> bossDups = new List<string>()
        {
            {"Hades Escape"},
            {"Hades I"},
            {"Hades II"},
            {"Blizzard Lord (Cups)"},
            {"Volcano Lord (Cups)"},
            {"Cerberus (Cups)"},
            {"Hades Cups"},
            {"Pete Cups"},
            {"Pete OC II"},
            {"Cloud (1)"},
            {"Cloud (2)"},
            {"Leon (1)"},
            {"Leon (2)"},
            {"Leon (3)"},
            {"Tifa (1)"},
            {"Tifa (2)"},
            {"Yuffie (1)"},
            {"Yuffie (2)"},
            {"Yuffie (3)"},
            //NOTE: temp solution, just don't hint seifer at all for now.
            //seifer 1 is always shadow roxas as of this note and all other seifers except tutorial don't work
            {"Seifer"},
            {"Seifer (1)"},
            {"Seifer (2)"},
            {"Seifer (3)"},
            {"Seifer (4)"},
        };

        public Dictionary<string, string> bossNameConversion = new Dictionary<string, string>()
        {
            {"Armor Xemnas I", "ArmoredXemnas1"},
            {"Armor Xemnas II", "ArmoredXemnas2"},
            {"Axel (Data)", "DataAxel"},
            {"Axel I", "Axel1"},
            {"Axel II", "Axel"},
            {"Barbossa", "Barbossa"},
            {"Blizzard Lord", "BlizzardLord"},
            {"Blizzard Lord (Cups)", "BlizzardLord"},
            {"Boat Pete", "BoatPete"},
            {"Cerberus", "Cerberus"},
            {"Cerberus (Cups)", "Cerberus"},
            {"Cloud", "Cloud"},
            {"Cloud (1)", "Cloud"},
            {"Cloud (2)", "Cloud"},
            {"Dark Thorn", "DarkThorn"},
            {"Demyx", "HBDemyx"},
            {"Demyx (Data)", "DataDemyx"},
            {"Final Xemnas", "FinalXemnas"},
            {"Final Xemnas (Data)", "DataFinalXemnas"},
            {"Grim Reaper I", "GrimReaper1"},
            {"Grim Reaper II", "GrimReaper"},
            {"Groundshaker", "GroundShaker"},
            {"Hades", "Hades"},
            {"Hades Cups", "Hades"},
            {"Hades Escape", "Hades"},
            {"Hades I", "Hades"},
            {"Hades II", "Hades"},
            {"Hades II (1)", "Hades"},
            {"Hayner", "Hayner"},
            {"Hercules", "Hercules"},
            {"Hostile Program", "HostileProgram"},
            {"Hydra", "Hydra"},
            {"Jafar", "GenieJafar"},
            {"Larxene", "Larxene"},
            {"Larxene (Data)", "LarxeneData"},
            //{"Lingering Will", "LingeringWill"},
            {"Leon", "Leon"},
            {"Leon (1)", "Leon"},
            {"Leon (2)", "Leon"},
            {"Leon (3)", "Leon"},
            {"Lexaeus", "Lexaeus"},
            {"Lexaeus (Data)", "LexaeusData"},
            {"Luxord", "Luxord"},
            {"Luxord (Data)", "DataLuxord"},
            {"Marluxia", "Marluxia"},
            {"Marluxia (Data)", "MarluxiaData"},
            {"MCP", "MCP"},
            {"Oogie Boogie", "OogieBoogie"},
            {"Past Pete", "OldPete"},
            {"Pete", "DCPete"},
            {"Pete Cups", "DCPete"},
            {"Pete OC II", "OCPete"},
            {"Pete TR", "DCPete"},
            {"Prison Keeper", "PrisonKeeper"},
            {"Riku", "Riku"},
            {"Roxas", "Roxas"},
            {"Roxas (Data)", "DataRoxas"},
            {"Saix", "Saix"},
            {"Saix (Data)", "DataSaix"},
            {"Sark", "Sark"},
            {"Scar", "Scar"},
            {"Seifer", "Seifer"},
            {"Seifer (1)", "Seifer"},
            {"Seifer (2)", "Seifer"},
            {"Seifer (3)", "Seifer"},
            {"Seifer (4)", "Seifer"},
            {"Sephiroth", "Sephiroth"},
            {"Setzer", "Setzer"},
            {"Shadow Stalker", "ShadowStalker"},
            {"Shan-Yu", "ShanYu"},
            {"Storm Rider", "StormRider"},
            {"Terra", "LingeringWill"},
            {"The Beast", "Beast"},
            {"The Experiment", "Experiment"},
            {"Thresholder", "Thresholder"},
            {"Tifa", "Tifa"},
            {"Tifa (1)", "Tifa"},
            {"Tifa (2)", "Tifa"},
            {"Twilight Thorn", "TwilightThorn"},
            {"Vexen", "Vexen"},
            {"Vexen (Data)", "VexenData"},
            {"Vivi", "Vivi"},
            {"Volcano Lord", "VolcanoLord"},
            {"Volcano Lord (Cups)", "VolcanoLord"},
            {"Xaldin", "Xaldin"},
            {"Xaldin (Data)", "DataXaldin"},
            {"Xemnas", "Xemnas1"},
            {"Xemnas (Data)", "DataXemnas"},
            {"Xigbar", "Xigbar"},
            {"Xigbar (Data)", "DataXigbar"},
            {"Yuffie", "Yuffie"},
            {"Yuffie (1)", "Yuffie"},
            {"Yuffie (2)", "Yuffie"},
            {"Yuffie (3)", "Yuffie"},
            {"Zexion", "Zexion"},
            {"Zexion (Data)", "ZexionData"},
        };

        // if we're playing boss rando, we don't want to deal with the progression checks "Hades" and "DCPete" since they aren't
        // the keys for Hades and Pete in the data.BossList dictionary.
        public static Dictionary<string, string> mismatchedBossNames = new Dictionary<string, string>()
        {
            { "Hades", "Hades II (1)" },
            { "DCPete", "Pete TR" },
            { "OCPete", "Pete OC II" }
        };
    }
}
